BOOTSECTOR_OBJ := \
	$(MODULE_BUILD_DIR)/disk.o    \
	$(MODULE_BUILD_DIR)/console.o \
	$(MODULE_BUILD_DIR)/entry.o

$(BOOTSECTOR_OBJ): ASFLAGS := $(I386_16_ASFLAGS)
$(MODULE_BUILD_DIR)/bootsector.a: $(BOOTSECTOR_OBJ) $(MODULE)/module.mk
	$(AR) $(ARFLAGS) $@ $(BOOTSECTOR_OBJ)
